### ISSUE TITLE
[epic] Diginomics v0.1

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/openrevolution#19]
A diginomics site providing grounding in economics of digital (info) economy and toolkit (concepts and templates) for solving key micro and macro challenges e.g. sustaining data sharing in X area (e.g. carbon data) or addressing tech monopolies.

## Acceptance

- [ ] Content DB with notes listing all the major existing content we have

### Prep

- [x] A10 booted **✅2023-01-06**
- [ ] initial SCQH and especially hypothesis **✅2023-01-06**
- [ ] Overall content DB with notes @theo-cox 

### Diginomics 101 / FAQ

- [ ] Sketch questions
- [ ] Answer first set of questions @theo-cox 

### Landing page

- [ ] Sketch out motivation **🚧2023-01-09 ...**

**Comment by theo-cox** [comment]
@rufuspollock have created stubs for each model type (reduced to 5) although I forgot to do pull requests for a couple. I'll do an overview page tomorrow

**Comment by rufuspollock** [comment]
@theo-cox did you get to the overview page in the end?

**Comment by theo-cox** [comment]
No I got too hung up on how to do a nice diagram and forgot my own principle of just shipping stuff. I'll do this week. I've also decided I want to split conditional payments into separate prizes and RRs pages after all...

**Comment by theo-cox** [comment]
**Agreed next actions 11/04/2023**

Process notes out of today’s meeting (if possible)
Update the building blocks
Revenue model
User fees
Upfront funding
Open / free
Maybe explain open as slightly different from free. E.g. youtube largely free, but not open …
Complementary goods to anything
Blending
Add complementary goods to anything
Mixed open licensing
Non-commercial, other price discrimination
How you can build your revenue model
Sketch out decision trees …??
Diginomics 101 tweaking …
