### ISSUE TITLE
Incentive Model Taxonomy

### ISSUE THREAD

**Issue by theo-cox** [life-itself/openrevolution#22]
When I'm doing mechanism/business model design for data sharing, I want to easily understand what options are out there, how they relate to one another and how to choose between them so that I can select the most suitable one and justify my choice to external stakeholders.

## Acceptance

- [ ] Taxonomy created

## Tasks

- [ ] Brainstorm model types **done**
- [ ] Write model descriptions **Here: https://docs.google.com/document/d/1AIsM9QZQKa2VvsrV4sbrFg7Aj6JGy6sAdO8LAsY6Wd4/edit# and Prizes here: https://docs.google.com/document/d/1qqR6uI4vgXyd1IJJJwSK9f7Jpf-YH1-p8WrF8F4BITM/edit#heading=h.zer6hoz4qs1i [also lots of work in iMed which this is summarised from]**
- [ ] Do draft taxonomy **p10 here: https://docs.google.com/document/d/1qqR6uI4vgXyd1IJJJwSK9f7Jpf-YH1-p8WrF8F4BITM/edit#heading=h.nlsvtgtyyqz9**
- [ ] Discuss and iterate
- [ ] Finalise

**Comment by rufuspollock** [comment]
@theo-cox i've updated acceptance to give a bit of  roadmap of how i think we proceed. Does this look correct? do you want to create specific issues ofr the next task or two here?

**Comment by theo-cox** [comment]
> @theo-cox i've updated acceptance to give a bit of roadmap of how i think we proceed. Does this look correct? do you want to create specific issues ofr the next task or two here?

@rufuspollock done and linked above (the bullet points weren't worth an issue, imo
